### PR TITLE
Add note about Schmidt Financial support

### PR DESCRIPTION
**Pull request by fperez**

### CODE REVIEW

**Comment by cboettig** [comment]
:+1: thanks! 

(unfortunately we don't have a way to automate deploy to https://ds4e.berkeley.edu since IT controls the servers there, but I'll pull this down and send it over ye olde FTP to their 'staging' pool.  (Still need to get the mailchimp set up, drop in image credits and a few other tweaks anyhow.)

**Comment by fperez** [comment]
Curious - are we not allowed to configure a domain that we serve from github pages? I know that gh pages can serve external domains, but I don't know if that's possible with campus sub-domains. Do you know?

**Comment by cboettig** [comment]
Right, my understanding is that Berkeley's policies won't allow it. You need access to the DNS records and would have to point the DNS at GitHub for that work, and I believe they don't permit pointing the DNS record at any host that is external to campus.  (at least that's my understanding, would probably have to follow up with the powers-at-be to get a more precise statement of the policy.  I wonder if it will change).

Meanwhile the FTP sync to staging in https://ds4e.berkeley.edu/ seems to go live immediately now, and Gary set up the SSL cert as well so I think it's workable.

**Comment by fperez** [comment]
Awesome, and thanks for the clarification - I figured as much but it's good to have confirmation!

**Comment by fperez** [comment]
And it seems we have a pretty workable workflow, so we can stick to this for now. Bigger fish to fry and all that - very happy to have this setup!

**Pull request merged**
